### ISSUE TITLE
Labs 14-17 Need updating

### ISSUE THREAD

**Issue by christianh814** [RedHatWorkshops/openshiftv3-workshop#12]
We need to update labs 14-17 with the supported Spring Boot method.

**Comment by christianh814** [comment]
Thoughts @VeerMuchandi ? We should really be using RH's Springboot/OpenJDK builders.

Here are my thoughts

* We can "collapse" labs 14 and 15 into one lab called "Using custom s2i builder image" and replace lab 18 with this new lab.
* Create a new set of labs that will be 14-17 using the supported RH Java Images.

(cc: @piggyvenus @nickschuetz)

**Comment by VeerMuchandi** [comment]
we can do separate lab on "Using custom s2i builder image" as you suggested. But why replace lab 18? Lab 18 teaches a different concept of changing code on the fly.
