### ISSUE TITLE
change userxx to userXX in asciidoc branch

### ISSUE THREAD

**Issue by gnunn1** [RedHatWorkshops/openshiftv3-workshop#19]
Currently in the asciidoc branch the workshop is using ```userxx``` everywhere. I would suggest that this be modified to ```userXX```, this prevents people from accidentally creating artifacts with ```userxx``` via copying and pasting since names in OpenShift do not allow uppercase. This was one of the benefits of the ```UserName``` scheme in the original labs.

Change it in the labs is easy enough via sed and appears to work fine for me:

```sed -i 's/userxx/userXX/g' *.adoc```

**Comment by christianh814** [comment]
@gnunn1 What branch are you working off of?

**Comment by gnunn1** [comment]
asciidoc as per title :)

**Comment by christianh814** [comment]
@samueltauil Can you take a look at this?
