### ISSUE TITLE
Confusion with docker image name

### ISSUE THREAD

**Issue by debianmaster** [RedHatWorkshops/openshiftv3-workshop#5]
during workshop i got a lot of question on name of  docker image name veermuchandi/weclome

https://github.com/RedHatWorkshops/openshiftv3-workshop/blob/master/1.%20Create%20App%20From%20a%20Docker%20Image.md

this needs to be made made more clear

**Comment by christianh814** [comment]
This has been addressed and we are now using the redhatworkshops repos
